### ISSUE TITLE
Abandon JSend

### ISSUE THREAD

**Issue by dcousens** [common-blockchain/cb-express-router#6]
`jsend` seems a bit overly verbose,  and the need to handle the two states `fail` and `error` seem a bit redundant for a client.

@rubensayshi any ideas?  What have you used before/currently?

**Comment by rubensayshi** [comment]
hmm the difference between fail and error can be a bit awkward but tbh it's not all that bad and it makes sense to have different state for input failure and server errors.

I never really considered using a standard for something like this, for our own API we use http codes and for all errs we return `{code: , msg: }` and in the SDK translate those back into exception/error classes.

I think the only issue we had with jsend was that I made a mistake doing it manually somewhere once and that we had some misunderstandings between when there's no results wether the result would be `null` or `""` or `{}`.

**Comment by dcousens** [comment]
@rubensayshi I've personally fallen in favour of just an 400 Error + message for problems,  or 200 + response JSON.
It is really simple to handle...
